[package]
name = "skrf-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "WASM bindings for skrf-core"

[lib]
crate-type = ["cdylib"]

[dependencies]
skrf-core = { path = "../skrf-core" }
wasm-bindgen.workspace = true
js-sys.workspace = true
